version: "3"

services:
  database:
    build: .
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U llm-slack-bot" ]
      interval: 2s
      timeout: 1s
      retries: 5
    ports:
      - "5433:5432"
    environment:
      - "POSTGRES_HOST=${POSTGRES_HOST}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${POSTGRES_USER}"
    volumes:
      - ./vector_data:/var/lib/postgresql/data

volumes:
  vector_data:
